apps/urls.py
from django.urls import include,path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('<str:username>/feedback',views.feedback_view, name='feedback'),
    path('<str:username>/edit',views.editprofile, name='editprofile'),
    path('createblog/',views.createblog, name='createblog'),
    path('blog/<str:shortname>',views.blog_view, name='blog_view'),
    path('blog/<str:shortname>/edit',views.editblog, name='editblog'),
    
    path('<str:username>/changeprofilepic/',views.profilepic, name='profilepic'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_change_form.html'), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),


    path('<str:username>/',views.profile, name='profile'),
]

testsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    #path('hospital/', include('hospital.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from datetime import datetime
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class Blog(models.Model):
    image = models.ImageField(upload_to='blog/image/')
    name = models.CharField(max_length=100)
    text = models.TextField()
    shortname =  models.CharField(max_length=20)
    template = models.FileField(upload_to='blog/template/')

class ProfilePicture(models.Model):
    img = models.ImageField(upload_to='profilepic/',default='profilepic/default.jpg',)#ProcessedImageField(upload_to='profilepic/',processors=[ResizeToFill(100,100)] , default='profilepic/default.jpg', format='JPEG' , options ={'quality': 60})

    def __str__(self):
        return (Account.objects.get(id=self.id).email)

class FeedbackClass(models.Model):
    email = models.CharField(max_length=100)
    feedback = models.TextField()

    def __str__(self):
        return (self.email)


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, first_name , last_name , password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
		    email = self.normalize_email(email),
		    username = username,
            first_name = first_name,
            last_name = last_name
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, first_name , last_name , password):
		user = self.create_user(
		    email = self.normalize_email(email),
		    password = password,
		    username = username,
            first_name = first_name,
            last_name = last_name,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

class user(models.Model):

    dob=models.DateField(default=datetime(1990,1,1))
    sex = models.CharField(max_length=10)
    bio = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    pincode = models.IntegerField(default=0)

    def __str__(self):
        return (Account.objects.get(id=self.id).email)



class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email' , max_length=60 , unique=True)
    username = models.CharField(max_length=60 , unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True )
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50 , default='')
    country = models.CharField(max_length=50 , default='')
    phone_number = models.IntegerField(default=0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']

    objects = MyAccountManager()

    def __str__(self):
        return (self.first_name+' '+self.last_name)

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True

apps/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ValidationError
from .models import ProfilePicture , user ,Blog
from PIL import Image
from django.core.files import File
#from django.forms.widgets import *

class ProfilePictureForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = ProfilePicture
        fields = ('img', 'x', 'y', 'width', 'height', )
        widgets = {
            'img': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    def save(self):
        photo = super(ProfilePictureForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.img)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.img.path)

        return photo


class UserForm(forms.ModelForm):
    dob = forms.DateField(widget=forms.DateInput(attrs={'type' : 'date'}),label='Date of Birth')
    sex=forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder' : 'Enter Sex'}), label='Sex', max_length=10 )
    bio = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'  , 'placeholder' : 'Enter Bio'} ),label='Bio' , required=False )
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' , 'placeholder' : 'Enter Address'}),label='Full Address' )
    pincode= forms.CharField(widget=forms.NumberInput(attrs={'class': 'col-auto', 'placeholder' : 'Enter Pincode'}))


    
    class Meta:
        model = user
        fields = ('dob','sex','bio','address','pincode')

class BlogForm(forms.ModelForm):
    image = forms.ImageField(label="Change Picture" , required=True , )
    name = forms.CharField(max_length=100 , required=True , )
    text = forms.CharField(widget=forms.TextInput() , required=True , )
    shortname = forms.CharField(max_length=20 , required=True , )
    template = forms.FileField(required=True, )

    class Meta:
        model = Blog
        fields=('image','name','text','shortname','template')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/{{log.url}}">{{log.name }}<span class="sr-only">(current)</span></a>
          </li>
          {% if not profile.welcome %}
          <li class="nav-item">
            <a class="nav-link" href="/{{register.url}}">{{ register.name }}</a>
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/{{profile.url}}">{{ profile.name }}</a>
              <a class="dropdown-item" href="/{{profile.url}}/changeprofilepic">Update Profile Picture</a>
              <a class="dropdown-item" href="/{{profile.url}}/edit">Edit Details</a>
              <a class="dropdown-item" href="/{{profile.url}}/feedback">Feedback</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/logout">Log out</a>
            </div>
          </li>
          
          <li class="nav-item">
            <a class="nav-link disabled" href="" tabindex="-1" aria-disabled="true">{{ profile.welcome }}</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </head>


  <body>
    {% block content %}

    {% endblock %}
    <p></p>

    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>


  <footer class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="footer-copyright">
      <div class="container">
      Developed by : ©{{copyright.name}}<br>      
      contact details:<br>Phone :
      {{copyright.phone_number}}, Email:
      {{copyright.email}} <br>
      </div>
    </div>
  </footer>
</html>

templates/changeprofilepic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    -->
    
    <nav class="navbar navbar-inverse">
      <a class="navbar-brand" href="/">My Site</a>
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/{{log.url}}">{{log.name }}<span class="sr-only">(current)</span></a>
          </li>
          {% if not profile.welcome %}
          <li class="nav-item">
            <a class="nav-link" href="/{{register.url}}">{{ register.name }}</a>
          </li>
          {% else %}
          <li class="dropdown">
            <a class="dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="item" href="/{{profile.url}}">{{ profile.name }}</a>
              <li><a class="item" href="/{{profile.url}}/changeprofilepic">Update Profile Picture</a>
              <li><a class="item" href="/{{profile.url}}/edit">Edit Details</a>
              <li><a class="item" href="/{{profile.url}}/feedback">Feedback</a>
              <div class="divider"></div>
              <li><a class="item" href="/logout">Log out</a>
            </ul>
          </li>
          
          <li class="nav-item">
            <a class="nav-link disabled" href="" tabindex="-1" aria-disabled="true">{{ profile.welcome }}</a>
          </li>
          {% endif %}
        </ul>
        <form class="navbar-form navbar-left">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </head>


  <body>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.0.0-beta/cropper.min.css"/>

    <div class="container">
      
      <!-- FORM TO UPLOAD THE IMAGES -->
      <form class="container"  method="post" enctype="multipart/form-data" id="formUpload">{% csrf_token %}
            <h1>Change Profile Picture</h1>
            
            Current Profile Picture:
            <img src="{{ form.instance.img.url }}" alt="" style="width:100px;height:100px;" >
            <br>
            <br>
            <tr>
              <th>
                <label for="id_img">Upload Profile Picture:</label>
              </th>
              <td>
                <input type="file" class="btn btn-default" name="img" accept="image/*" required id="id_img">
                <input type="hidden" name="x" id="id_x">
                <input type="hidden" name="y" id="id_y"><input type="hidden" name="width" id="id_width">
                <input type="hidden" name="height" id="id_height">
              </td>
            </tr>
            <br>
            <br>
        </form>
      <!-- MODAL TO CROP THE IMAGE -->
      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                <span class="glyphicon glyphicon-zoom-in">zooom in</span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                <span class="glyphicon glyphicon-zoom-out">zoom out</span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.0.0-beta/cropper.min.js"></script>
    <script>
    $(function () {
    /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
    $("#id_img").change(function () {
    if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
    $("#image").attr("src", e.target.result);
    $("#modalCrop").modal("show");
    }
    reader.readAsDataURL(this.files[0]);
    }
    });
    /* SCRIPTS TO HANDLE THE CROPPER BOX */
    var $image = $("#image");
    var cropBoxData;
    var canvasData;
    $("#modalCrop").on("shown.bs.modal", function () {
    $image.cropper({
    viewMode: 1,
    aspectRatio: 1/1,
    minCropBoxWidth: 200,
    minCropBoxHeight: 200,
    ready: function () {
    $image.cropper("setCanvasData", canvasData);
    $image.cropper("setCropBoxData", cropBoxData);
    }
    });
    }).on("hidden.bs.modal", function () {
    cropBoxData = $image.cropper("getCropBoxData");
    canvasData = $image.cropper("getCanvasData");
    $image.cropper("destroy");
    });
    $(".js-zoom-in").click(function () {
    $image.cropper("zoom", 0.1);
    });
    $(".js-zoom-out").click(function () {
    $image.cropper("zoom", -0.1);
    });
    /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
    $(".js-crop-and-upload").click(function () {
    var cropData = $image.cropper("getData");
    $("#id_x").val(cropData["x"]);
    $("#id_y").val(cropData["y"]);
    $("#id_height").val(cropData["height"]);
    $("#id_width").val(cropData["width"]);
    $("#formUpload").submit();
    });
    });
    </script>

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  -->
  </body>


  <footer class="navbar navbar-inverse">
    <div class="footer-copyright">
      <div class="container">
      Developed by : ©{{copyright.name}}<br>      
      contact details:<br>Phone :
      {{copyright.phone_number}}, Email:
      {{copyright.email}} <br>
      </div>
    </div>
  </footer>
</html>

templates/edit.html
{% extends 'base.html' %}
{% block content %}
        <form  method="post" class="container" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="contain">
                <h1>Edit your details</h1>
                <div class="row">
                    <div class="col">
                        <div class="box">
                            {% for field in form %}
                                <div class="field">
                                    <span class="text" for="{{ field.id_for_label }}"> {{ field.label }}</span>
                                    {{ field }}
                                    <p></p>
                                    {% for error in field.errors %}
                                        <p class="ferror">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <button type='submit' class="btn btn-secondary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endblock %}

templates/editblog.html
{% extends 'base.html' %}
{% block content %}
        <form  method="post" class="container" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="contain">
                <h1>Enter or change Blog details :</h1>
                <div class="row">
                    <div class="col">
                        <div class="box">
                            {% for field in form %}
                                <div class="field">
                                    <span class="text" for="{{ field.id_for_label }}"> {{ field.label }}</span>
                                    {{ field }}
                                    <p></p>
                                    {% for error in field.errors %}
                                        <p class="ferror">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <button type='submit' class="btn btn-secondary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endblock %}

templates/feedback.html
{% extends 'base.html' %}
{% block content %}
<h1>Please Give a Feedback</h1>
        <form  method="post" class="col s12" >{% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Write your Feedback</label>
                <textarea class="form-control" name='feedback' id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button type='submit' class="btn btn-secondary">Submit Feedback</button>
        </form>
        
        {% endblock %}

templates/home.html
<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
</style>

    
{% extends 'base.html' %}
{% block content %}
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>Home Page</h1>
      <p class="lead text-muted">Welcome to Mysite</p>
      <p>
        <!--<a href="#" class="btn btn-primary my-2">Main call to action</a>-->
        {% if profile.admin %}
        <a href="/createblog" class="btn btn-secondary my-2">Create new Blog</a>
        {% endif %}
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
      {% if blogs %}
        {% for blog in blogs %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          
            <!--<svg  class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyCTUFDq2yLfY8ZGid4uxoFLxLeRAJBRH9o_rvMiXd5uSfDlXM&s">
                <title>Placeholder</title>
                <rect  width="100%" height="100%" fill="#55595c"/>
                
                <text x="50%" y="50%" fill="#eceeef" dy=".3em"></text>
            </svg>-->
            <img src="{{blog.image.url}}">
            <div class="card-body">
              <h2>{{blog.name}}</h2>
              <p class="card-text">{{blog.text}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-sm btn-outline-secondary" href="/blog/{{blog.shortname}}">View</a>
                  {% if profile.admin %}
                  <a class="btn btn-sm btn-outline-secondary" href="/blog/{{blog.shortname}}/edit">Edit</a>
                  {% endif %}
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}
        
      </div>
    </div>
  </div>

</main>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>

templates/login.html
{% extends 'base.html' %}
{% block content %}
<form class="container" method="post">{% csrf_token %}
<h1>Login </h1>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="text" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
  </div>
  
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %} 
  {% endif %}
  <a class="" href="/password_reset">
      Forgot Password ? Click Here
  </a><br><br>

  <button type="submit" class="btn btn-primary">Sign in</button>
  <a class="" href="/register">
      Not Registered ? Create an account
  </a>
</form>
{% endblock %}

templates/userinfo.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Profile</h1>

    <img src="{{pp.url}}" alt="" style="width:100px;height:100px;" >
    <p>User id :{{user.id}} <br></p>
    <p>Username :{{username}} <br></p>
    <p>Name :{{user.first_name}} {{user.last_name}} <br></p>
    <p>Email :{{user.email}} <br></p>
    <p>Country :{{user.country}} <br></p>
    <p>Phone number : {{user.phone_number}} <br></p>
    <p>Address :{{user1.address}} <br></p>
    <p>Date of Birth :{{user1.dob}} <br></p>
    
    <p>Gender :{{user1.sex}} <br></p>
    <p>Pincode :{{user1.pincode}} <br></p>
    <p>Bio : {{user1.bio}} <br></p>
    <p><a class="btn btn-secondary" href="./edit">edit</a></p>
    <a class="" href="/password_change">Change Password ? click here</a>
</div>
 {% endblock %}